dataset:
  bounds: &europe_bounds
    lat_min: 34.5
    lat_max: 71.2
    lon_min: -25.0
    lon_max: 30.0
  GDHY:
    path: /beegfs/muduchuru/data/GDHY
    bounds: *europe_bounds
  SAGE:
    path: "/beegfs/muduchuru/data/SAGE_crop_calendar/Wheat.crop.calendar.fill.nc.gz"
    bounds: *europe_bounds
  MSWX:
    bounds: *europe_bounds
    variables:
      pr:
        path: '/beegfs/muduchuru/data/MSWX/zarr/pr_mswep_daily_1989-2020.zarr'
        var_name: precipitation
      tasmin:
        path: '/beegfs/muduchuru/data/MSWX/zarr/tasmin_mswx_daily_1989-2020.zarr'
        var_name: air_temperature
      tasmax:
        path: '/beegfs/muduchuru/data/MSWX/zarr/tasmax_mswx_daily_1989-2020.zarr'
        var_name: air_temperature
    time_range:
      start: "2000-01-01"
      end: "2010-12-31"

indices:
  pr:
    # - name: daily_pr_intensity
    #   function: xclim.indices.daily_pr_intensity
    #   variables: [pr]
    #   args:
    #     thresh: "10 mm/day"
    #     freq: "YS"
    #     op: ">="

    # - name: Rx1day
    #   function: xclim.indices.max_n_day_precipitation_amount
    #   variables: [pr]
    #   args:
    #     window: 1
    #     freq: "YS"

    # - name: Rx3day
    #   function: xclim.indices.max_n_day_precipitation_amount
    #   variables: [pr]
    #   args:
    #     window: 3
    #     freq: "YS"

    # - name: dry_days
    #   function: xclim.indices.dry_days
    #   variables: [pr]
    #   args:
    #     thresh: "0.2 mm/d"
    #     freq: "YS"
    #     op: "<"

    # - name: dry_spell_frequency
    #   function: xclim.indices.dry_spell_frequency
    #   variables: [pr]
    #   args:
    #     thresh: "1.0 mm"
    #     window: 3
    #     freq: "YS"
    #     resample_before_rl: true
    #     op: "sum"

    # - name: dry_spell_max_length
    #   function: xclim.indices.dry_spell_max_length
    #   variables: [pr]
    #   args:
    #     thresh: "1.0 mm"
    #     window: 3
    #     freq: "YS"
    #     resample_before_rl: true
    #     op: "sum"

    # - name: dry_spell_total_length
    #   function: xclim.indices.dry_spell_total_length
    #   variables: [pr]
    #   args:
    #     thresh: "1.0 mm"
    #     window: 3
    #     freq: "YS"
    #     resample_before_rl: true
    #     op: "sum"

    - name: r75p
      function: xclim.indices.days_over_precip_thresh
      variables: [pr, p75]
      args:
        freq: 'YS'
      preprocess:
        quantiles:
          p75:
            input: pr
            operation: quantile
            kwargs:
              q: 0.75
              dim: time
              keep_attrs: true

    # - name: f75p
    #   function: xclim.indices.fraction_over_precip_thresh
    #   variables: [pr, p75]
    #   args:
    #     freq: 'YS'
    #   preprocess:
    #     quantiles:
    #       p75:
    #         input: pr
    #         operation: quantile
    #         kwargs:
    #           q: 0.75
    #           dim: time
    #           keep_attrs: true

output:
  zarr_pattern: "{name}_{start}-{end}_{freq}.zarr"
  start: 1989
  end: 2019
